### ISSUE TITLE
Update KaTeX version to 0.16.7 and later

### ISSUE THREAD

**Issue by cogsandsquigs** [kwshi/rehype-katex-svelte#4]
Firstly, KaTeX should be updated again because the newest version is 0.16.7, instead of the old 0.15.0.

Secondly, do you know of any way to automatically rebuild/recompile this plugin when KaTeX updates? Possibly through a github action of some sort? Just so that I don't have to keep bugging you :p.

**Comment by cogsandsquigs** [comment]
I found [this stackoverflow thread](https://stackoverflow.com/questions/58465057/trigger-a-github-action-when-another-repository-creates-a-new-release), it may prove useful.

**Comment by kwshi** [comment]
I bumped the version in 9144b02ca0bd8a46c08742bcf2f9df77590f70aa and published to npm; please double-check and let me know to make sure that it's working correctly (what with updates and all).

You're right-- I should have some kind of auto-update set up (using dependabot or something, together with some GH actions to re-release on push, but I'm not totally sure how to go about doing that yet. Maybe I'll try to take a look soon; say, within the next week.)
